blank_issues_enabled: false
contact_links:
  - name: 💖 [Sponsors only] Feature requests / Help / Questions
    url: https://github.com/sponsors/privatenumber/
    about: Need help ASAP? Get prioritized help for all your questions and issues!

  - name: 📚 Contribution guide
    url: https://github.com/privatenumber/tsx/blob/master/CONTRIBUTING.md
    about: Learn more about contributing to this project
